#!/bin/bash -x
git checkout -b red
git checkout -b blue
read -p "Press [Enter] key to continue "

touch blue
git add blue
git commit -m "needed some blue"
read -p "Press [Enter] key to continue "

git checkout red
read -p "Press [Enter] key to continue "

touch red
git add red
git commit -m "needed some red"
touch yellow 
git add yellow
git commit -m "needed some green"
read -p "uh oh.. yellow was supposed to be green. Let's fix that"

git mv yellow green
git commit --fixup=:/green
read -p "oh.. no we should have added some blue first. Let's fix that"





